name: deploy

on: workflow_dispatch

concurrency:
  group: deploys
  cancel-in-progress: true

defaults:
  run:
    working-directory: website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: website
          sparse-checkout-cone-mode: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        shell: bash
        run: bun install

      - name: Build
        shell: bash
        run: bun run build



  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
      # permissions:
      #   contents: read
      #   deployments: write
  #   steps:
  #     - name: Deploy Website
  #       uses: cloudflare/pages-action@v1
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         accountId:
  #         projectName: 
  #         directory: website/dist
  #         gitHubToken: ${{ secrets.GITHUB_TOKEN }}
