name: Publish

on:
  workflow_dispatch:
  release:
    types: [released]

concurrency: pypi

jobs:	
  publish:
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: 3.x

      - name: Install
        run: python -m pip install --upgrade .

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}