name: Test

on: 
  workflow_dispatch:
  # push:
  #   paths: '**.py'
  # pull_request:
  #   paths: '**.py'
  #   types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: python -m pip install --upgrade .[test]

      - name: Test
        uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          report-title: Report
          click-to-expand: false